version: '3.7'

services:
  base: &base
    image: lets
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app

  lint:
    image: golangci/golangci-lint:v1.24.0
    working_dir: /app
    volumes:
      - ./:/app
    command: golangci-lint run -v -c .golang-ci.yaml

  test:
    <<: *base
    environment:
      LETS_CONFIG_DIR: ..
    entrypoint: [go, test, ./..., -v, -coverprofile=coverage.out]

  test-bats:
    <<: *base
    command: |
      bash -c '
        go build -o /usr/bin/lets *.go
        if [[ -n "${LETSOPT_TEST}" ]]; then
          bats tests/"${LETSOPT_TEST}"
        else
          bats tests
        fi
      '
