version: '3.7'

services:
  base: &base
    image: lets
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app

  staticheck:
    <<: *base
    command: staticcheck ./...

  test:
    <<: *base
    environment:
      LETS_CONFIG_DIR: ..
    entrypoint: [go, test, ./..., -v, -coverprofile=coverage.out]
