on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go: [1.13.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        env:
          LETS_CONFIG_DIR: ..
        run: go test ./... -v
      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./bin v1.24.0
          ./bin/golangci-lint run -v
